{% set name = "boututils" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1225a90bd6807508867b1f345d001bf69a36c1f456083e7b618a4238773fc044

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - numpy
    - matplotlib-base
    - scipy
    - h5py
    - future
    - netcdf4

test:
  imports:
    - boututils
  requires:
    - pytest
  commands:
    - pytest --pyargs boututils

about:
  home: https://github.com/boutproject/boututils
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Python utilities for BOUT++
  description: |
    pip-package of what was previously found in BOUT-dev/tools/pylib/boututils
    Note that BOUT-dev/tools/pylib/boututils will likely be replaced by this
    repo in BOUT++ v4.4.0.
    > **NOTE**: This package will likely be superseded by xBOUT in the near future
  dev_url: https://github.com/boutproject/boututils

extra:
  recipe-maintainers:
    - johnomotani
    - ZedThree
    - loeiten
